### ISSUE TITLE
При обновлении версии Salesman - ошибка.

### ISSUE THREAD

**Issue by PrimechaevRuslan** [vladandreevg/salesmancrm#7]
root@crm:/$ php /var/www/salesman/_install/update.php
Start at 03.09 16:00

Fatal error: Uncaught Exception: SafeMySQL: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(CURRENT_TIMESTAMP) COMMENT 'дата создания' AFTER `did`,
                        CHANGE ' at line 2. Full query: [
                ALTER TABLE `salesman_entry`
                        CHANGE COLUMN `datum` `datum` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT 'дата создания' AFTER `did`,
                        CHANGE COLUMN `datum_do` `datum_do` DATETIME NULL DEFAULT NULL COMMENT 'дата обработки обращения' AFTER `datum`
                ] in /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php:623
Stack trace:
#0 /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php(483): SafeMySQL->error('SafeMySQL: You ...')
#1 /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php(140): SafeMySQL->rawQuery('\r\n\t\tALTER TABLE...')
#2 /var/www/salesman/_install/update.php(1178): SafeMySQL->query('\r\n\t\tALTER TABLE...')
#3 {main}
  thrown in /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php on line 623

**Comment by vladandreevg** [comment]
> root@crm:/$ php /var/www/salesman/_install/update.php Start at 03.09 16:00
> 
> Fatal error: Uncaught Exception: SafeMySQL: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(CURRENT_TIMESTAMP) COMMENT 'дата создания' AFTER `did`, CHANGE ' at line 2. Full query: [ ALTER TABLE `salesman_entry` CHANGE COLUMN `datum` `datum` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT 'дата создания' AFTER `did`, CHANGE COLUMN `datum_do` `datum_do` DATETIME NULL DEFAULT NULL COMMENT 'дата обработки обращения' AFTER `datum` ] in /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php:623 Stack trace: #0 /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php(483): SafeMySQL->error('SafeMySQL: You ...') #1 /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php(140): SafeMySQL->rawQuery('\r\n\t\tALTER TABLE...') #2 /var/www/salesman/_install/update.php(1178): SafeMySQL->query('\r\n\t\tALTER TABLE...') #3 {main} thrown in /var/www/salesman/vendor/colshrapnel/safemysql/safemysql.class.php on line 623

Зависит от типа вашей БД и её настроек.
Попробуйте выполнить следующие запросы одновременно (например через Adminer или phpMyAdmin):

```
SET sql_mode='NO_ENGINE_SUBSTITUTION,ALLOW_INVALID_DATES';
ALTER TABLE `salesman_entry` CHANGE COLUMN `datum` `datum` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'дата создания' AFTER `did`, CHANGE COLUMN `datum_do` `datum_do` DATETIME NULL DEFAULT NULL COMMENT 'дата обработки обращения' AFTER `datum`;
```

префикс "salesman_" надо заменить на свой, если он отличается. На сколько мне известно, такая ошибка возникает если заменить тип поля timestamp на datetime и связан с более строгим sql_mode. Нашел старую базу со старой структурой. На MySQL 8.0 запрос прошел

**Comment by vladandreevg** [comment]
затем можно запустить скрипт обновления снова

**Comment by PrimechaevRuslan** [comment]
Подправил скрипт обновления, все заработало.
В MySQL конструкция DEFAULT (CURRENT_TIMESTAMP) является синтаксически некорректной. Вместо этого нужно использовать DEFAULT CURRENT_TIMESTAMP без скобок.

**Comment by vladandreevg** [comment]
Да, в предыдущих ревизиях затесалась такая ошибка. Она уже устранена от 20.07.2024, после релиза правда
